stages:
  - build

build-debian:
  image: debian:buster
  tags:
    - librem5
  before_script:
    - apt-get -y update
    - apt-get -y install build-essential 
    - apt-get -y build-dep .
  stage: build
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build -Dgtk_doc=true
    - ninja -C _build
    - ninja -C _build meson-libhandy-doc
    - xvfb-run ninja -C _build test

