include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'

variables:
  MANIFEST_PATH: 'demo/org.gnome.Adwaita1.Demo.json'
  FLATPAK_MODULE: 'libadwaita'
  FLATPAK_BUILD_DIR: build
  ABI_CHECKER_IMAGE: "registry.gitlab.gnome.org/gnome/libadwaita/abi-checker:v2"
  DOCS_IMAGE: "registry.gitlab.gnome.org/gnome/libadwaita/docs:v2"

stages:
  - build
  - publish
  - deploy

api-visibility:
  stage: build
  before_script: []
  script:
    - ./.gitlab-ci/api-visibility.sh

doc:
  image: $DOCS_IMAGE
  stage: build
  tags:
    - flatpak
  variables:
    MESON_ARGS: >-
      -Dgtk_doc=true
      -Dtests=false
      -Dvapi=false
  script:
    - meson --prefix=/app ${MESON_ARGS} _build
    - ninja -C _build
    - mv _build/doc/libadwaita-1 _doc/
  artifacts:
    paths:
      - _doc

build-flatpak:
  extends: '.flatpak'
  stage: build
  before_script: []
  variables:
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: 'org.gnome.Adwaita1.Demo'
    BUNDLE: 'org.gnome.Adwaita1.Demo.flatpak'

abi-check:
  image: $ABI_CHECKER_IMAGE
  stage: build
  variables:
    LAST_ABI_BREAK: "11849510ba90790093ae130a3e46033b1f908e57"
  script:
    - ./.gitlab-ci/check-abi ${LAST_ABI_BREAK} $(git rev-parse HEAD)

refresh-doc:
  stage: publish
  only:
    refs:
    - 'main'
  script:
    - "curl -X POST -F token=${PAGES_TRIGGER_TOKEN} -F ref=pages https://gitlab.gnome.org/api/v4/projects/14079/trigger/pipeline"

asan:
  image: registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master
  stage: build
  tags:
    - flatpak
  variables:
    MESON_ARGS: >-
      -Dintrospection=disabled
      -Db_sanitize=address
      --werror
    ASAN_OPTIONS: fast_unwind_on_malloc=0
    LSAN_OPTIONS: suppressions=../data/leak-suppress.txt
    TEST_RUN_ARGS: -t10
  script:
    - flatpak-builder --user --disable-rofiles-fuse --build-only flatpak_app ${MANIFEST_PATH} --stop-at=${FLATPAK_MODULE}
    - flatpak build flatpak_app meson --prefix=/app ${MESON_ARGS} _build
    - flatpak build flatpak_app ninja -C _build
    - flatpak-builder --user --disable-rofiles-fuse --finish-only flatpak_app ${MANIFEST_PATH}
    - xvfb-run -a -s "-screen 0 1024x768x24"
      flatpak-builder --user --disable-rofiles-fuse --run flatpak_app ${MANIFEST_PATH} \
      meson test -C _build --no-stdsplit --print-errorlogs ${TEST_RUN_ARGS}

nightly:
  extends: '.publish_nightly'
  dependencies: ['build-flatpak']
  needs: ['build-flatpak']
