include:
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak_ci_initiative.yml'

variables:
  MANIFEST_PATH: 'examples/org.gnome.Adwaita.Demo.json'
  FLATPAK_MODULE: 'libadwaita'
  FLATPAK_BUILD_DIR: build
  ABI_CHECKER_IMAGE: "registry.gitlab.gnome.org/gnome/libadwaita/abi-checker:v1"
  DOCS_IMAGE: "registry.gitlab.gnome.org/gnome/libadwaita/docs:v1"

stages:
  - build
  - publish

api-visibility:
  stage: build
  before_script: []
  script:
    - ./.gitlab-ci/api-visibility.sh

doc:
  image: $DOCS_IMAGE
  stage: build
  tags:
    - flatpak
  variables:
    MESON_ARGS: >-
      -Dbuild-tests=false
      -Dgtk_doc=true
      -Dvapi=false
  script:
    - meson --prefix=/app ${MESON_ARGS} _build
    - ninja -C _build
    - mv _build/doc/libadwaita-1 _doc/
  artifacts:
    paths:
      - _doc

build-flatpak:
  extends: '.flatpak'
  stage: build
  before_script: []
  variables:
    RUNTIME_REPO: 'https://nightly.gnome.org/gnome-nightly.flatpakrepo'
    APP_ID: 'org.gnome.Adwaita.Demo'
    BUNDLE: 'org.gnome.Adwaita.Demo.flatpak'

abi-check:
  image: $ABI_CHECKER_IMAGE
  stage: build
  variables:
    LAST_ABI_BREAK: "da5bf6689886754d7aa0fd86af76783ce22e3b31"
  script:
    - ./.gitlab-ci/check-abi ${LAST_ABI_BREAK} $(git rev-parse HEAD)

refresh-doc:
  stage: publish
  only:
    refs:
    - 'main'
  script:
    - "curl -X POST -F token=${PAGES_TRIGGER_TOKEN} -F ref=pages https://gitlab.gnome.org/api/v4/projects/14079/trigger/pipeline"
